startMainMenu();
  mainMenuItem("paintmari_menueng_home", "Home", "indexeng.htm");
  mainMenuItem("paintmari_menueng_b1", "Works", "javascript:;");
    startSubmenu(); 
      mainMenuItem("paintmari_menueng_ongoing", "Ongoing", "ongoingeng.htm");
      mainMenuItem("paintmari_menueng_b1_2", "Paintings", "javascript:;");
        startSubmenu();
          submenuItem("Bittersweet Series", "pbittersweetserieseng.htm");
          submenuItem("Myth, Symbols", "pmythsymbolseng.htm");
          submenuItem("Figuration, Abstraction", "pfigurationabstractioneng.htm");
        endSubmenu();
      mainMenuItem("paintmari_menueng_b1_3", "Works on Paper", "javascript:;");
        startSubmenu();
          submenuItem("Bittersweet Series", "wopbittersweetserieseng.htm");
          submenuItem("Myth, Symbols", "wopmythsymbolseng.htm");
          submenuItem("Figuration, Abstraction", "wopfigurationabstractioneng.htm");
        endSubmenu();
      mainMenuItem("paintmari_menueng_b1_4", "Projects", "javascript:;");
        startSubmenu();
          submenuItem("The Seed Project", "theseedprojecteng.htm");
          submenuItem("The Book Project", "thebookprojecteng.htm");
        endSubmenu();
    endSubmenu();
  mainMenuItem("paintmari_menueng_b2", "Statement", "statementeng.htm");
  mainMenuItem("paintmari_menueng_b3", "Biography", "biographyeng.htm");
  mainMenuItem("paintmari_menueng_b4", "Contact", "contacteng.htm");
endMainMenu();
