startMainMenu();
  mainMenuItem("paintmari_menujap_home", "ホーム", "indexjap.htm");
  mainMenuItem("paintmari_menujap_b1", "作品", "javascript:;");
    startSubmenu(); 
      mainMenuItem("paintmari_menujap_ongoing", "制作中", "ongoingjap.htm");
      mainMenuItem("paintmari_menujap_b1_2", "油彩", "javascript:;");
        startSubmenu();
          submenuItem("ビタースイート・シリーズ", "pbittersweetseriesjap.htm");
          submenuItem("神話、象徴", "pmythsymbolsjap.htm");
          submenuItem("具象、抽象", "pfigurationabstractionjap.htm");
        endSubmenu();
      mainMenuItem("paintmari_menujap_b1_3", "紙作品", "javascript:;");
        startSubmenu();
          submenuItem("ビタースイート・シリーズ", "wopbittersweetseriesjap.htm");
          submenuItem("神話、象徴", "wopmythsymbolsjap.htm");
          submenuItem("具象、抽象", "wopfigurationabstractionjap.htm");
        endSubmenu();
      mainMenuItem("paintmari_menujap_b1_4", "プロジェクト", "javascript:;");
        startSubmenu();
          submenuItem("種のプロジェクト", "theseedprojectjap.htm");
          submenuItem("本のプロジェクト", "thebookprojectjap.htm");
        endSubmenu();
    endSubmenu();
  mainMenuItem("paintmari_menujap_b2", "アート観", "statementjap.htm");
  mainMenuItem("paintmari_menujap_b3", "プロフィール", "biographyjap.htm");
  mainMenuItem("paintmari_menujap_b4", "コンタクト", "contactjap.htm");
endMainMenu();
